// ===================== HARD-CODED QUIZ DATA =====================
// بەشداربووان دەتوانن ئاسان پرسیار زیادبکەن - تەنها لێرە دەق و هەڵبژاردنەکان زیادبکە
// To add more questions: just copy a block and change the text/options!

export interface HardcodedQuestion {
  id: string
  categoryBadini: string
  categorySorani: string
  textBadini: string
  textSorani: string
  option1Badini: string
  option1Sorani: string
  option2Badini: string
  option2Sorani: string
  option3Badini: string
  option3Sorani: string
  option4Badini: string
  option4Sorani: string
  correctAnswer: number // 1, 2, 3, or 4
}

export const questions: HardcodedQuestion[] = [
  // ===================== ئایینی / Religious =====================
  {
    id: 'q1',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'چەند سورەت لە قورئانا پیرۆزدا هەیە؟',
    textSorani: 'چەند سورەت لە قورئانی پیرۆزدا هەیە؟',
    option1Badini: '١١٤',
    option1Sorani: '١١٤',
    option2Badini: '١٢٠',
    option2Sorani: '١٢٠',
    option3Badini: '١١٠',
    option3Sorani: '١١٠',
    option4Badini: '١٠٠',
    option4Sorani: '١٠٠',
    correctAnswer: 1,
  },
  {
    id: 'q2',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'پێغەمبەرێ ئیسلام کێیە؟',
    textSorani: 'پێغەمبەری ئیسلام کێیە؟',
    option1Badini: 'حەزرەتی عیسا',
    option1Sorani: 'حەزرەتی عیسا',
    option2Badini: 'حەزرەتی موحەمەد ﷺ',
    option2Sorani: 'حەزرەتی موحەمەد ﷺ',
    option3Badini: 'حەزرەتی موسا',
    option3Sorani: 'حەزرەتی موسا',
    option4Badini: 'حەزرەتی ئیبراهیم',
    option4Sorani: 'حەزرەتی ئیبراهیم',
    correctAnswer: 2,
  },
  {
    id: 'q3',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'چەند رێکەی نژوورێ هەیە لە ئیسلامێدا؟',
    textSorani: 'چەند رکنی نوێژ هەیە لە ئیسلامدا؟',
    option1Badini: '٤',
    option1Sorani: '٤',
    option2Badini: '٦',
    option2Sorani: '٦',
    option3Badini: '٥',
    option3Sorani: '٥',
    option4Badini: '٣',
    option4Sorani: '٣',
    correctAnswer: 3,
  },
  {
    id: 'q4',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'مانگێ ڕەمەزان چ مانگە؟',
    textSorani: 'مانگی ڕەمەزان چ مانگە؟',
    option1Badini: 'مانگێ ڕۆژووگرتنە',
    option1Sorani: 'مانگی ڕۆژووگرتنە',
    option2Badini: 'مانگێ قوربانە',
    option2Sorani: 'مانگی قوربانە',
    option3Badini: 'مانگێ زەکاتە',
    option3Sorani: 'مانگی زەکاتە',
    option4Badini: 'مانگێ حەجە',
    option4Sorani: 'مانگی حەجە',
    correctAnswer: 1,
  },
  {
    id: 'q5',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'کوا قورئانا پیرۆز لە مانگێ چ دابەز؟',
    textSorani: 'قورئانی پیرۆز لە چ مانگێک دابەزی؟',
    option1Badini: 'شەعبان',
    option1Sorani: 'شەعبان',
    option2Badini: 'ڕەمەزان',
    option2Sorani: 'ڕەمەزان',
    option3Badini: 'موحەڕەم',
    option3Sorani: 'موحەڕەم',
    option4Badini: 'زولحەججە',
    option4Sorani: 'زولحەججە',
    correctAnswer: 2,
  },
  // ===================== زانستی / Scientific =====================
  {
    id: 'q6',
    categoryBadini: 'زانستی',
    categorySorani: 'زانستی',
    textBadini: 'خۆر چ ناوچەیەکە؟',
    textSorani: 'خۆر چ ناوچەیەکە؟',
    option1Badini: 'هەسارە',
    option1Sorani: 'هەسارە',
    option2Badini: 'ئەستێرە',
    option2Sorani: 'ئەستێرە',
    option3Badini: 'مانگ',
    option3Sorani: 'مانگ',
    option4Badini: 'کۆمەتا',
    option4Sorani: 'کۆمەتا',
    correctAnswer: 2,
  },
  {
    id: 'q7',
    categoryBadini: 'زانستی',
    categorySorani: 'زانستی',
    textBadini: 'ئاو هەڵگەڕاوی هەسارەی چەند پلەیە؟',
    textSorani: 'ئاوی هەڵگەڕاو لە چ پلەیەکدا دەبێتە بەفر؟',
    option1Badini: '٠ پلە',
    option1Sorani: '٠ پلە',
    option2Badini: '١٠٠ پلە',
    option2Sorani: '١٠٠ پلە',
    option3Badini: '٥٠ پلە',
    option3Sorani: '٥٠ پلە',
    option4Badini: '-١٠ پلە',
    option4Sorani: '-١٠ پلە',
    correctAnswer: 1,
  },
  {
    id: 'q8',
    categoryBadini: 'زانستی',
    categorySorani: 'زانستی',
    textBadini: 'چەند هەسارە لە سیستمێ خۆرێدا هەیە؟',
    textSorani: 'چەند هەسارە لە سیستەمی خۆریدا هەیە؟',
    option1Badini: '٧',
    option1Sorani: '٧',
    option2Badini: '٨',
    option2Sorani: '٨',
    option3Badini: '٩',
    option3Sorani: '٩',
    option4Badini: '١٠',
    option4Sorani: '١٠',
    correctAnswer: 2,
  },
  {
    id: 'q9',
    categoryBadini: 'زانستی',
    categorySorani: 'زانستی',
    textBadini: 'هەناسەدانی مرۆڤ چ بەکاردێنیت؟',
    textSorani: 'هەناسەدانی مرۆڤ چ بەکاردێنێت؟',
    option1Badini: 'ئۆکسجین',
    option1Sorani: 'ئۆکسجین',
    option2Badini: 'نایتڕۆجین',
    option2Sorani: 'نایتڕۆجین',
    option3Badini: 'کاربۆن',
    option3Sorani: 'کاربۆن',
    option4Badini: 'هیدرۆجین',
    option4Sorani: 'هیدرۆجین',
    correctAnswer: 1,
  },
  // ===================== مێژوویی / Historical =====================
  {
    id: 'q10',
    categoryBadini: 'مێژوویی',
    categorySorani: 'مێژوویی',
    textBadini: 'سەڵاحەدین ئەیوبی لە چ شەڕێکێدا سەرکەوت؟',
    textSorani: 'سەڵاحەدین ئەیوبی لە چ شەڕێکدا سەرکەوت؟',
    option1Badini: 'شەڕێ حەتین',
    option1Sorani: 'شەڕی حەتین',
    option2Badini: 'شەڕێ بەدر',
    option2Sorani: 'شەڕی بەدر',
    option3Badini: 'شەڕێ ئوحود',
    option3Sorani: 'شەڕی ئوحود',
    option4Badini: 'شەڕێ خەندەق',
    option4Sorani: 'شەڕی خەندەق',
    correctAnswer: 1,
  },
  {
    id: 'q11',
    categoryBadini: 'مێژوویی',
    categorySorani: 'مێژوویی',
    textBadini: 'ئەمریکا لە ساڵێ چ دۆزرایەوە؟',
    textSorani: 'ئەمریکا لە چ ساڵێکدا دۆزرایەوە؟',
    option1Badini: '١٤٩٢',
    option1Sorani: '١٤٩٢',
    option2Badini: '١٥٠٠',
    option2Sorani: '١٥٠٠',
    option3Badini: '١٦٠٠',
    option3Sorani: '١٦٠٠',
    option4Badini: '١٤٠٠',
    option4Sorani: '١٤٠٠',
    correctAnswer: 1,
  },
  {
    id: 'q12',
    categoryBadini: 'مێژوویی',
    categorySorani: 'مێژوویی',
    textBadini: 'کەڵکەمەرگێن لە شارێ چ داگیرکر؟',
    textSorani: 'قەڵای کەڵکەمەرگ لە چ شارێکدا داگیرکرا؟',
    option1Badini: 'هەولێرێ',
    option1Sorani: 'هەولێر',
    option2Badini: 'سلێمانیێ',
    option2Sorani: 'سلێمانی',
    option3Badini: 'دهۆکێ',
    option3Sorani: 'دهۆک',
    option4Badini: 'کەرکووکێ',
    option4Sorani: 'کەرکووک',
    correctAnswer: 1,
  },
  // ===================== جوگرافی / Geography =====================
  {
    id: 'q13',
    categoryBadini: 'جوگرافی',
    categorySorani: 'جوگرافی',
    textBadini: 'پایتەختێ کوردستانێ (عێراق) چ شارە؟',
    textSorani: 'پایتەختی کوردستان (عێراق) چ شارە؟',
    option1Badini: 'هەولێرێ',
    option1Sorani: 'هەولێر',
    option2Badini: 'سلێمانیێ',
    option2Sorani: 'سلێمانی',
    option3Badini: 'دهۆکێ',
    option3Sorani: 'دهۆک',
    option4Badini: 'کەرکووکێ',
    option4Sorani: 'کەرکووک',
    correctAnswer: 1,
  },
  {
    id: 'q14',
    categoryBadini: 'جوگرافی',
    categorySorani: 'جوگرافی',
    textBadini: 'ڕووبارێ نیل لە کو قاتە؟',
    textSorani: 'ڕووباری نیل لە کوێدا تێپەڕێت؟',
    option1Badini: 'میسڕ',
    option1Sorani: 'میسڕ',
    option2Badini: 'عێراق',
    option2Sorani: 'عێراق',
    option3Badini: 'تورکیا',
    option3Sorani: 'تورکیا',
    option4Badini: 'ئێران',
    option4Sorani: 'ئێران',
    correctAnswer: 1,
  },
  {
    id: 'q15',
    categoryBadini: 'جوگرافی',
    categorySorani: 'جوگرافی',
    textBadini: 'چیایێ ئەڤرێست لە کو هەیە؟',
    textSorani: 'چیای ئەڤرێست لە کوێدا هەیە؟',
    option1Badini: 'هیندستان',
    option1Sorani: 'هیندستان',
    option2Badini: 'نیپال',
    option2Sorani: 'نیپال',
    option3Badini: 'چین',
    option3Sorani: 'چین',
    option4Badini: 'تورکیا',
    option4Sorani: 'تورکیا',
    correctAnswer: 2,
  },
  // ===================== وەرزشی / Sports =====================
  {
    id: 'q16',
    categoryBadini: 'وەرزشی',
    categorySorani: 'وەرزشی',
    textBadini: 'جامێ جیهانیێ فۆتبۆل چەند ساڵان ئەنجام دەبیت؟',
    textSorani: 'جامی جیهانی فۆتبۆل چەند ساڵان جارێک ئەنجام دەدرێت؟',
    option1Badini: '٢ ساڵ',
    option1Sorani: '٢ ساڵ',
    option2Badini: '٣ ساڵ',
    option2Sorani: '٣ ساڵ',
    option3Badini: '٤ ساڵ',
    option3Sorani: '٤ ساڵ',
    option4Badini: '٥ ساڵ',
    option4Sorani: '٥ ساڵ',
    correctAnswer: 3,
  },
  {
    id: 'q17',
    categoryBadini: 'وەرزشی',
    categorySorani: 'وەرزشی',
    textBadini: 'تیمێ فۆتبۆلێ چەند یاریزان لە یاریگا هەیە؟',
    textSorani: 'تیمی فۆتبۆل چەند یاریزان لە یاریگادا هەیە؟',
    option1Badini: '٩',
    option1Sorani: '٩',
    option2Badini: '١٠',
    option2Sorani: '١٠',
    option3Badini: '١١',
    option3Sorani: '١١',
    option4Badini: '١٢',
    option4Sorani: '١٢',
    correctAnswer: 3,
  },
  // ===================== گشتی / General =====================
  {
    id: 'q18',
    categoryBadini: 'گشتی',
    categorySorani: 'گشتی',
    textBadini: 'ڕۆژا هەتاو چ کاتژمێر دەستپێدکەت؟',
    textSorani: 'ڕۆژ هەتاو چ کاتژمێر دەستپێدەکات؟',
    option1Badini: '٦ کاتژمێر',
    option1Sorani: '٦ کاتژمێر',
    option2Badini: '١٢ کاتژمێر',
    option2Sorani: '١٢ کاتژمێر',
    option3Badini: '٣ کاتژمێر',
    option3Sorani: '٣ کاتژمێر',
    option4Badini: '٩ کاتژمێر',
    option4Sorani: '٩ کاتژمێر',
    correctAnswer: 1,
  },
  {
    id: 'q19',
    categoryBadini: 'گشتی',
    categorySorani: 'گشتی',
    textBadini: 'زمانێ کوردی چ بنەماڵەی زمانە؟',
    textSorani: 'زمانی کوردی چ بنەماڵەی زمانە؟',
    option1Badini: 'سامی',
    option1Sorani: 'سامی',
    option2Badini: 'هیندوئەورووپی',
    option2Sorani: 'هیندوئەورووپی',
    option3Badini: 'تورکی',
    option3Sorani: 'تورکی',
    option4Badini: 'دڕاویدی',
    option4Sorani: 'دڕاویدی',
    correctAnswer: 2,
  },
  {
    id: 'q20',
    categoryBadini: 'گشتی',
    categorySorani: 'گشتی',
    textBadini: 'ساڵێ چەند ڕۆژ هەیە؟',
    textSorani: 'ساڵێک چەند ڕۆژ هەیە؟',
    option1Badini: '٣٦٥',
    option1Sorani: '٣٦٥',
    option2Badini: '٣٦٠',
    option2Sorani: '٣٦٠',
    option3Badini: '٣٧٠',
    option3Sorani: '٣٧٠',
    option4Badini: '٣٥٥',
    option4Sorani: '٣٥٥',
    correctAnswer: 1,
  },
  // ===================== More Religious =====================
  {
    id: 'q21',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'نژوورێ بەیانی چەند رەکعاتە؟',
    textSorani: 'نوێژی بەیانی چەند رەکعاتە؟',
    option1Badini: '٢',
    option1Sorani: '٢',
    option2Badini: '٣',
    option2Sorani: '٣',
    option3Badini: '٤',
    option3Sorani: '٤',
    option4Badini: '١',
    option4Sorani: '١',
    correctAnswer: 1,
  },
  {
    id: 'q22',
    categoryBadini: 'ئایینی',
    categorySorani: 'ئایینی',
    textBadini: 'حەج لە کو ئەنجام دەبیت؟',
    textSorani: 'حەج لە کوێ ئەنجام دەدرێت؟',
    option1Badini: 'مەککە',
    option1Sorani: 'مەککە',
    option2Badini: 'مەدینە',
    option2Sorani: 'مەدینە',
    option3Badini: 'قودس',
    option3Sorani: 'قودس',
    option4Badini: 'قاہرە',
    option4Sorani: 'قاہرە',
    correctAnswer: 1,
  },
  // ===================== More Science =====================
  {
    id: 'q23',
    categoryBadini: 'زانستی',
    categorySorani: 'زانستی',
    textBadini: 'مانگ لە چ ڕۆژێکێدا دەسوڕیتەوە دەوری زەوی؟',
    textSorani: 'مانگ لە چ ڕۆژێکدا دەسوڕێتەوە بە دەوری زەویدا؟',
    option1Badini: '٢٧ ڕۆژ',
    option1Sorani: '٢٧ ڕۆژ',
    option2Badini: '٣٠ ڕۆژ',
    option2Sorani: '٣٠ ڕۆژ',
    option3Badini: '١٥ ڕۆژ',
    option3Sorani: '١٥ ڕۆژ',
    option4Badini: '٦٠ ڕۆژ',
    option4Sorani: '٦٠ ڕۆژ',
    correctAnswer: 1,
  },
  {
    id: 'q24',
    categoryBadini: 'زانستی',
    categorySorani: 'زانستی',
    textBadini: 'ئەندامی گەورەترین لە جەستەی مرۆڤ چییە؟',
    textSorani: 'ئەندامی گەورەترین لە جەستەی مرۆڤ چییە؟',
    option1Badini: 'دڵ',
    option1Sorani: 'دڵ',
    option2Badini: 'جگەر',
    option2Sorani: 'جگەر',
    option3Badini: 'پێست',
    option3Sorani: 'پێست',
    option4Badini: 'مێشک',
    option4Sorani: 'مێشک',
    correctAnswer: 3,
  },
  // ===================== More History =====================
  {
    id: 'q25',
    categoryBadini: 'مێژوویی',
    categorySorani: 'مێژوویی',
    textBadini: 'شەڕێ جیهانیێ دوایەن لە چ ساڵێ تەواو بوو؟',
    textSorani: 'شەڕی جیهانی دووەم لە چ ساڵێکدا تەواو بوو؟',
    option1Badini: '١٩٤٠',
    option1Sorani: '١٩٤٠',
    option2Badini: '١٩٤٥',
    option2Sorani: '١٩٤٥',
    option3Badini: '١٩٥٠',
    option3Sorani: '١٩٥٠',
    option4Badini: '١٩٣٥',
    option4Sorani: '١٩٣٥',
    correctAnswer: 2,
  },
  // ===================== More Geography =====================
  {
    id: 'q26',
    categoryBadini: 'جوگرافی',
    categorySorani: 'جوگرافی',
    textBadini: 'وڵاتێ گەورەترین لە جیهان چ وڵاتە؟',
    textSorani: 'وڵاتی گەورەترین لە جیهان چ وڵاتە؟',
    option1Badini: 'چین',
    option1Sorani: 'چین',
    option2Badini: 'ئەمریکا',
    option2Sorani: 'ئەمریکا',
    option3Badini: 'ڕووسیا',
    option3Sorani: 'ڕووسیا',
    option4Badini: 'کەنەدا',
    option4Sorani: 'کەنەدا',
    correctAnswer: 3,
  },
  {
    id: 'q27',
    categoryBadini: 'جوگرافی',
    categorySorani: 'جوگرافی',
    textBadini: 'دەریاچەی گەورەترین لە جیهان چ دەریاچەیە؟',
    textSorani: 'دەریاچەی گەورەترین لە جیهان چ دەریاچەیە؟',
    option1Badini: 'دەریای خەزەر',
    option1Sorani: 'دەریای خەزەر',
    option2Badini: 'دەریاچەی ڤیکتۆریا',
    option2Sorani: 'دەریاچەی ڤیکتۆریا',
    option3Badini: 'دەریاچەی باکال',
    option3Sorani: 'دەریاچەی باکال',
    option4Badini: 'دەریاچەی سوپیریەر',
    option4Sorani: 'دەریاچەی سوپیریەر',
    correctAnswer: 4,
  },
  // ===================== Culture =====================
  {
    id: 'q28',
    categoryBadini: 'کولتووری',
    categorySorani: 'کولتووری',
    textBadini: 'نەورۆز لە چ ڕۆژێکێ ئەنجام دەبیت؟',
    textSorani: 'نەورۆز لە چ ڕۆژێکدا ئەنجام دەدرێت؟',
    option1Badini: '٢١ مارس',
    option1Sorani: '٢١ مارس',
    option2Badini: '١ مارس',
    option2Sorani: '١ مارس',
    option3Badini: '١ ئەپریل',
    option3Sorani: '١ ئەپریل',
    option4Badini: '٢١ ئەپریل',
    option4Sorani: '٢١ ئەپریل',
    correctAnswer: 1,
  },
  {
    id: 'q29',
    categoryBadini: 'کولتووری',
    categorySorani: 'کولتووری',
    textBadini: 'ئامێرێ کوردی چ ناوە؟ ئامێرێ تەوڕە...',
    textSorani: 'ئامێری کوردی چ ناوە؟ ئامێری تەوڕە...',
    option1Badini: 'تەوڕە',
    option1Sorani: 'تەوڕە',
    option2Badini: 'عود',
    option2Sorani: 'عود',
    option3Badini: 'کەمان',
    option3Sorani: 'کەمان',
    option4Badini: 'پiano',
    option4Sorani: 'پیانۆ',
    correctAnswer: 1,
  },
  {
    id: 'q30',
    categoryBadini: 'کولتووری',
    categorySorani: 'کولتووری',
    textBadini: 'جلکەی کوردی ناوێ چییە؟',
    textSorani: 'جلکەی کوردی ناوی چییە؟',
    option1Badini: 'شەلوار',
    option1Sorani: 'شەلوار',
    option2Badini: 'چۆخە',
    option2Sorani: 'چۆخە',
    option3Badini: 'فەرەنجە',
    option3Sorani: 'فەرەنجە',
    option4Badini: 'کۆت',
    option4Sorani: 'کۆت',
    correctAnswer: 2,
  },
]

// ===================== GET UNIQUE CATEGORIES =====================
export function getCategories(lang: 'badini' | 'sorani'): { id: string; name: string }[] {
  const catMap = new Map<string, string>()
  questions.forEach(q => {
    const key = lang === 'badini' ? q.categoryBadini : q.categorySorani
    catMap.set(key, key)
  })
  return Array.from(catMap.entries()).map(([id, name]) => ({ id, name }))
}

// ===================== GET QUESTIONS BY CATEGORY =====================
export function getQuestionsByCategory(categoryName?: string): HardcodedQuestion[] {
  if (!categoryName || categoryName === 'تەڤایەتی' || categoryName === 'تەواوى') {
    return [...questions]
  }
  return questions.filter(q =>
    q.categoryBadini === categoryName || q.categorySorani === categoryName
  )
}

// ===================== SHUFFLE QUESTIONS =====================
export function shuffleQuestions(qs: HardcodedQuestion[]): HardcodedQuestion[] {
  const shuffled = [...qs]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}
